#!/usr/bin/ruby

t0 = Time.now
require_relative 'lib/lxd_driver'
require 'base64'

LXDriver.log_init

vm_name = ARGV[0]
image_path = ARGV[1]
target = ARGV[2]
disk_index = ARGV[3]
xml = ARGV[4]
vm_id = ARGV[5]

info = LXDriver.action_xml(Base64.decode64(xml))
disks = info.multiple_elements('DISK')
disk_info = info.device_info(disks, 'DISK', target)

disk_hash = info.disk(disk_info)
mapper = LXDriver.select_driver(disk_info['DRIVER'])
source = disk_hash.values[0]['source']
disk_id = source.split('.')[-1]
device = LXDriver.device_path(info, disk_id)

client = LXDClient.new
container = Container.get(vm_name, client)

mapper.run('map', source, device)
container.devices.update(disk_hash)

container.update

LXDriver.log_end(t0)
