#!/usr/bin/ruby

t0 = Time.now
require_relative 'lib/lxd_driver'

LXDriver.log_init

vm_name = ARGV[0]
mac = ARGV[1]
bridge = ARGV[2]
model = ARGV[3]
net_drv = ARGV[4]
host_nic = ARGV[5]
vm_id = ARGV[6]
host = ARGV[7]

info = LXDriver.action_xml
nics = info.multiple_elements('NIC')
nic_info = info.device_info(nics, 'NIC', mac)

client = LXDClient.new
container = Container.get(vm_name, client)

container.devices.update(info.nic(nic_info))
container.update

LXDriver.log_end(t0)
