#!/usr/bin/ruby

t0 = Time.now
require_relative 'lib/lxd_driver'

LXDriver.log_init

vm_name = ARGV[0]
iso_path = ARGV[2]
vm_id = ARGV[3]

info = LXDriver.action_xml

client = LXDClient.new
container = Container.get(vm_name, client)

context_hash = info.context
LXDriver.context(context_hash['context']['source'], 'map')
container.devices.update(context_hash)
container.update

LXDriver.log_end(t0)
